// <auto-generated />
using System;
using ApiTester.McpServer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTester.McpServer.Migrations
{
    [DbContext(typeof(ApiTesterDbContext))]
    [Migration("20260226090000_Day42_ResultClassification")]
    partial class Day42_ResultClassification : Migration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.OpenApiSpecEntity", b =>
                {
                    b.Property<Guid>("SpecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SpecJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SpecId");

                    b.HasIndex("ProjectId")
                        .IsUnique();

                    b.ToTable("OpenApiSpecs");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.ProjectEntity", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProjectId");

                    b.HasIndex("Name");

                    b.HasIndex("OwnerKey");

                    b.HasIndex("OwnerKey", "ProjectKey")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.TestCaseResultEntity", b =>
                {
                    b.Property<long>("TestCaseResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TestCaseResultId"));

                    b.Property<string>("BlockReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Blocked")
                        .HasColumnType("bit");

                    b.Property<int?>("Classification")
                        .HasColumnType("int");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Pass")
                        .HasColumnType("bit");

                    b.Property<string>("ResponseSnippet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestCaseResultId");

                    b.HasIndex("RunId");

                    b.ToTable("TestCaseResults");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.TestPlanEntity", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OperationId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId", "OperationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("TestPlans");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.TestRunEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("BaselineRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Blocked")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("Failed")
                        .HasColumnType("int");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int>("Passed")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<long>("TotalDurationMs")
                        .HasColumnType("bigint");

                    b.Property<int>("TotalCases")
                        .HasColumnType("int");

                    b.HasKey("RunId");

                    b.HasIndex("BaselineRunId");

                    b.HasIndex("ProjectId", "StartedUtc");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.OpenApiSpecEntity", b =>
                {
                    b.HasOne("ApiTester.McpServer.Persistence.Entities.ProjectEntity", "Project")
                        .WithOne("OpenApiSpec")
                        .HasForeignKey("ApiTester.McpServer.Persistence.Entities.OpenApiSpecEntity", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.TestCaseResultEntity", b =>
                {
                    b.HasOne("ApiTester.McpServer.Persistence.Entities.TestRunEntity", "Run")
                        .WithMany("Results")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.TestPlanEntity", b =>
                {
                    b.HasOne("ApiTester.McpServer.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany("TestPlans")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.TestRunEntity", b =>
                {
                    b.HasOne("ApiTester.McpServer.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany("Runs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTester.McpServer.Persistence.Entities.TestRunEntity", "BaselineRun")
                        .WithMany()
                        .HasForeignKey("BaselineRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("BaselineRun");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.ProjectEntity", b =>
                {
                    b.Navigation("OpenApiSpec");

                    b.Navigation("Runs");

                    b.Navigation("TestPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
