// <auto-generated />
using System;
using ApiTester.McpServer.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ApiTester.McpServer.Migrations
{
    [DbContext(typeof(ApiTesterDbContext))]
    partial class ApiTesterDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.22")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.OpenApiSpecEntity", b =>
                {
                    b.Property<Guid>("SpecId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SpecHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("nvarchar(64)");

                    b.Property<string>("SpecJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("SpecId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProjectId", "SpecHash")
                        .IsUnique();

                    b.ToTable("OpenApiSpecs");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.OrganisationEntity", b =>
                {
                    b.Property<Guid>("OrganisationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Slug")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("nvarchar(80)");

                    b.HasKey("OrganisationId");

                    b.HasIndex("Slug")
                        .IsUnique();

                    b.ToTable("Organisations");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.ProjectEntity", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ProjectKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("ProjectId");

                    b.HasIndex("Name");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("OwnerKey");

                    b.HasIndex("TenantId", "ProjectKey")
                        .IsUnique();

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Email")
                        .HasMaxLength(320)
                        .HasColumnType("nvarchar(320)");

                    b.Property<string>("ExternalId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("UserId");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.MembershipEntity", b =>
                {
                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(40)
                        .HasColumnType("nvarchar(40)");

                    b.HasKey("OrganisationId", "UserId");

                    b.HasIndex("UserId");

                    b.ToTable("Memberships");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.Property<Guid>("AuditEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<Guid>("ActorUserId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("MetadataJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TargetId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("TargetType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("AuditEventId");

                    b.HasIndex("OrganisationId", "CreatedUtc");

                    b.HasIndex("OrganisationId", "Action", "CreatedUtc");

                    b.ToTable("AuditEvents");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.RunAnnotationEntity", b =>
                {
                    b.Property<Guid>("AnnotationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("JiraLink")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("OwnerKey")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedUtc")
                        .HasColumnType("datetime2");

                    b.HasKey("AnnotationId");

                    b.HasIndex("RunId");

                    b.HasIndex("OwnerKey", "RunId");

                    b.ToTable("RunAnnotations");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.TestCaseResultEntity", b =>
                {
                    b.Property<long>("TestCaseResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("TestCaseResultId"));

                    b.Property<string>("BlockReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Blocked")
                        .HasColumnType("bit");

                    b.Property<int?>("Classification")
                        .HasColumnType("int");

                    b.Property<long>("DurationMs")
                        .HasColumnType("bigint");

                    b.Property<string>("FailureReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FlakeReasonCategory")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsFlaky")
                        .HasColumnType("bit");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("nvarchar(16)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("Pass")
                        .HasColumnType("bit");

                    b.Property<string>("ResponseSnippet")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("RunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int?>("StatusCode")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestCaseResultId");

                    b.HasIndex("RunId");

                    b.ToTable("TestCaseResults");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.TestPlanEntity", b =>
                {
                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("OperationId")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProjectId", "OperationId");

                    b.HasIndex("ProjectId");

                    b.ToTable("TestPlans");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.TestPlanDraftEntity", b =>
                {
                    b.Property<Guid>("DraftId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("CreatedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PlanJson")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("DraftId");

                    b.HasIndex("ProjectId");

                    b.ToTable("TestPlanDrafts");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.TestRunEntity", b =>
                {
                    b.Property<Guid>("RunId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Actor")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<Guid?>("BaselineRunId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Blocked")
                        .HasColumnType("int");

                    b.Property<DateTime>("CompletedUtc")
                        .HasColumnType("datetime2");

                    b.Property<string>("EnvironmentBaseUrl")
                        .HasMaxLength(2048)
                        .HasColumnType("nvarchar(2048)");

                    b.Property<string>("EnvironmentName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Failed")
                        .HasColumnType("int");

                    b.Property<string>("OperationId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<Guid>("OrganisationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("TenantId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("Passed")
                        .HasColumnType("int");

                    b.Property<string>("PolicySnapshotJson")
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("SpecId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("StartedUtc")
                        .HasColumnType("datetime2");

                    b.Property<int>("TotalCases")
                        .HasColumnType("int");

                    b.Property<long>("TotalDurationMs")
                        .HasColumnType("bigint");

                    b.HasKey("RunId");

                    b.HasIndex("BaselineRunId");

                    b.HasIndex("OrganisationId");

                    b.HasIndex("TenantId");

                    b.HasIndex("ProjectId", "StartedUtc");

                    b.HasIndex("SpecId");

                    b.ToTable("TestRuns");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.OpenApiSpecEntity", b =>
                {
                    b.HasOne("ApiTester.McpServer.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany("OpenApiSpecs")
                        .HasForeignKey("ApiTester.McpServer.Persistence.Entities.OpenApiSpecEntity", "ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.MembershipEntity", b =>
                {
                    b.HasOne("ApiTester.McpServer.Persistence.Entities.OrganisationEntity", "Organisation")
                        .WithMany("Memberships")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTester.McpServer.Persistence.Entities.UserEntity", "User")
                        .WithMany("Memberships")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("User");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.AuditEventEntity", b =>
                {
                    b.HasOne("ApiTester.McpServer.Persistence.Entities.OrganisationEntity", "Organisation")
                        .WithMany("AuditEvents")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.RunAnnotationEntity", b =>
                {
                    b.HasOne("ApiTester.McpServer.Persistence.Entities.TestRunEntity", "Run")
                        .WithMany("Annotations")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.TestCaseResultEntity", b =>
                {
                    b.HasOne("ApiTester.McpServer.Persistence.Entities.TestRunEntity", "Run")
                        .WithMany("Results")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.TestPlanEntity", b =>
                {
                    b.HasOne("ApiTester.McpServer.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany("TestPlans")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.TestPlanDraftEntity", b =>
                {
                    b.HasOne("ApiTester.McpServer.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany("TestPlanDrafts")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.TestRunEntity", b =>
                {
                    b.HasOne("ApiTester.McpServer.Persistence.Entities.OpenApiSpecEntity", "Spec")
                        .WithMany()
                        .HasForeignKey("SpecId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApiTester.McpServer.Persistence.Entities.TestRunEntity", "BaselineRun")
                        .WithMany()
                        .HasForeignKey("BaselineRunId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("ApiTester.McpServer.Persistence.Entities.OrganisationEntity", "Organisation")
                        .WithMany("Runs")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ApiTester.McpServer.Persistence.Entities.ProjectEntity", "Project")
                        .WithMany("Runs")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("Project");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.ProjectEntity", b =>
                {
                    b.HasOne("ApiTester.McpServer.Persistence.Entities.OrganisationEntity", "Organisation")
                        .WithMany("Projects")
                        .HasForeignKey("OrganisationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Organisation");

                    b.Navigation("OpenApiSpecs");

                    b.Navigation("Runs");

                    b.Navigation("TestPlanDrafts");

                    b.Navigation("TestPlans");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.OrganisationEntity", b =>
                {
                    b.Navigation("AuditEvents");

                    b.Navigation("Memberships");

                    b.Navigation("Projects");

                    b.Navigation("Runs");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.TestRunEntity", b =>
                {
                    b.Navigation("Annotations");

                    b.Navigation("Results");
                });

            modelBuilder.Entity("ApiTester.McpServer.Persistence.Entities.UserEntity", b =>
                {
                    b.Navigation("Memberships");
                });
#pragma warning restore 612, 618
        }
    }
}
